// backend/src/routes/export.js
// Task R8 (Rodina) — NOT YET IMPLEMENTED
// GET /api/export
const express = require("express");
const router = express.Router();

const {
  getActivitiesByCompany,
  getEmissionFactors,
} = require("../db/db");

const {
  calculateEmissions,
  calculateCompanyFootprint,
} = require("../engine/calculateEmissions");

router.get("/", (req, res) => {
  try {
    const companyId = Number(req.query.companyId || 1);

    const activities = getActivitiesByCompany(companyId);

    if (!activities || activities.length === 0) {
      return res.status(404).json({
        error: `No activities found for companyId ${companyId}`,
      });
    }

    const factors = getEmissionFactors();

    const calculated = activities
      .filter((a) => Number.isFinite(a.quantity))
      .map((a) => {
        try {
          const result = calculateEmissions(
            {
              type: a.type,
              quantity: a.quantity,
              unit: a.unit,
              date: a.date,
            },
            factors
          );

          return {
            ...result,
            type: a.type,
            quantity: a.quantity,
            unit: a.unit,
            date: a.date,
          };
        } catch {
          return null;
        }
      })
      .filter(Boolean);

    const footprint = calculateCompanyFootprint(calculated);

    const total =
      Number(footprint.totalCo2eKg) ||
      calculated.reduce(
        (sum, item) => sum + Number(item.co2e_kg || 0),
        0
      );

    const hotspotMap = {};

    calculated.forEach((item) => {
      hotspotMap[item.type] =
        (hotspotMap[item.type] || 0) +
        Number(item.co2e_kg || 0);
    });

    const hotspots = Object.entries(hotspotMap).sort(
      (a, b) => b[1] - a[1]
    );

    const hotspotRows = hotspots
      .map(
        ([type, emissions]) => `
          <tr>
            <td>${type}</td>
            <td>${emissions.toFixed(2)}</td>
          </tr>
        `
      )
      .join("");

    const activityRows = calculated
      .map(
        (item) => `
          <tr>
            <td>${item.date || ""}</td>
            <td>${item.type || ""}</td>
            <td>${item.quantity || ""}</td>
            <td>${item.unit || ""}</td>
            <td>${Number(item.co2e_kg || 0).toFixed(2)}</td>
          </tr>
        `
      )
      .join("");

    const html = `
<!DOCTYPE html>
<html>
<head>
  <meta charset="UTF-8">
  <title>CarbonWise Sustainability Report</title>

  <style>
    body {
      font-family: Arial, sans-serif;
      margin: 40px;
      line-height: 1.6;
    }

    h1 {
      margin-bottom: 5px;
    }

    .summary {
      border: 1px solid #ddd;
      border-radius: 10px;
      padding: 20px;
      margin: 25px 0;
    }

    .total {
      font-size: 30px;
      font-weight: bold;
    }

    table {
      width: 100%;
      border-collapse: collapse;
      margin: 15px 0 30px;
    }

    th,
    td {
      border: 1px solid #ddd;
      padding: 10px;
      text-align: left;
    }

    th {
      background: #f2f2f2;
    }

    .recommendations {
      border: 1px solid #ddd;
      border-radius: 10px;
      padding: 20px;
    }
  </style>
</head>

<body>

  <h1>CarbonWise Sustainability Report</h1>

  <p>Company ID: ${companyId}</p>

  <div class="summary">
    <h2>Carbon Footprint Summary</h2>

    <p class="total">
      ${total.toFixed(2)} kg CO2e
    </p>

    <p>
      Total Activities: ${calculated.length}
    </p>
  </div>

  <h2>Emission Hotspots</h2>

  <table>
    <tr>
      <th>Category</th>
      <th>Emissions (kg CO2e)</th>
    </tr>

    ${hotspotRows}
  </table>

  <h2>Emission Results</h2>

  <table>
    <tr>
      <th>Date</th>
      <th>Type</th>
      <th>Quantity</th>
      <th>Unit</th>
      <th>CO2e (kg)</th>
    </tr>

    ${activityRows}
  </table>

  <h2>Recommendations</h2>

  <div class="recommendations">
    <ul>
      <li>Reduce diesel consumption where possible.</li>
      <li>Improve electricity efficiency.</li>
      <li>Improve energy efficiency.</li>
      <li>Monitor high-emission categories.</li>
      <li>Consider cleaner energy alternatives.</li>
      <li>Use the What-If Simulator to test reduction scenarios.</li>
    </ul>
  </div>

  <p>Generated by CarbonWise</p>

</body>
</html>
`;

    res.setHeader(
      "Content-Type",
      "text/html; charset=utf-8"
    );

    res.setHeader(
      "Content-Disposition",
      'attachment; filename="carbonwise-summary.html"'
    );

    res.send(html);
  } catch (err) {
    console.error("[export]", err);

    res.status(500).json({
      error: err.message,
    });
  }
});

module.exports = router;